name: Dump Game Offsets
on: [workflow_dispatch]

jobs:
  dump_offsets:
    runs-on: windows-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install gdown
        run: pip install gdown

      - name: Download from Google Drive
        run: |
          gdown --folder "https://drive.google.com/drive/folders/1Kzwj7u5UV33OXBnFf5fghLXVI_gR2Jao" -O ./game_files
        continue-on-error: true

      - name: Download Il2CppDumper
        run: |
          # Link gốc chuẩn 100% bản mới nhất v6.7.46 (Đã thêm chữ -win-)
          curl -L -o dumper.zip https://github.com/Perfare/Il2CppDumper/releases/download/v6.7.46/Il2CppDumper-win-v6.7.46.zip
          Expand-Archive -Path dumper.zip -DestinationPath ./dumper

      - name: Run Dumper
        run: |
          $unity = Get-ChildItem -Path ./game_files -Recurse | Where-Object { $_.Name -match "UnityFramework|kgvn" } | Select-Object -First 1
          $metadata = Get-ChildItem -Path ./game_files -Recurse -Filter "global-metadata.dat" | Select-Object -First 1
          Write-Host "Binary: $($unity.FullName)"
          Write-Host "Metadata: $($metadata.FullName)"
          ./dumper/Il2CppDumper.exe $unity.FullName $metadata.FullName ./output
        continue-on-error: true

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: Game-Offsets
          path: ./output/script.json
